### ISSUE TITLE
Error with 1.0

### ISSUE THREAD

**Issue by huzefaKhalil** [dokastho/snprocess#1]
There is a an error now with this version of snprocess. It fails at the HWE step. The json files is below:

`{
    "1kG_dir": "/shops/onr_samples_group/clubhouse/GenotypeInfo2015_2018/Files_for_QC/",
    "inFile": "merge",
    "inDir": "/shops/onr_samples_group/clubhouse/PRS/Phase1/input/",
    "outDir": "/shops/onr_samples_group/clubhouse/PRS/usingSnprocess/Phase1/",
    "geno": 0.01,
    "mind": 0.05,
    "maf": 0.005,
    "hwe": 0.00001,
    "indep_pairwise": [50, 5, 0.5],
    "relatedness": 0.2
}
`

The error message is

`
plink  --bfile /shops/onr_samples_group/clubhouse/PRS/usingSnprocess/Phase1/merge --hwe 1e-05 --hwe-all --make-bed --out /shops/onr_samples_group/clubhouse/PRS/usingSnprocess/Phase1/qcplink
^^^ Process exited with error
`
Something went wrong when the temp file code was changed I am guessing. Also, the temp files "tmpplink[abc]" are now in the directory from where the command was run, not the output directory, or (preferably) a temp directory.

No rush on getting to this.

**Comment by dokastho** [comment]
yeah that's a simple fix, I just need to change the name of the temp file
to include the trailing slash

**Comment by dokastho** [comment]
should be all set

**Comment by huzefaKhalil** [comment]
Still doesn't work (1.0.1). Now it fails earlier at the first plink command

`
plink  --bfile /shops/onr_samples_group/clubhouse/PRS/Phase1/input/merge --missing --out tmp/plink
^^^ Process exited with error
`

**Comment by huzefaKhalil** [comment]
That was fixed easily by creating the 'tmp' directory!

**Comment by huzefaKhalil** [comment]
But still fails at HWE.

The problem is that it is looking at for the file
"/shops/onr_samples_group/clubhouse/PRS/usingSnprocess/Phase1/merge.bed"

for the HWE input. However, that file shouldn't be the input for that command. That file doesn't exist. It should use the output from the previous plink command as input for the HWE command.

**Comment by dokastho** [comment]
Ah ok. I'll take a closer look in a little bit!

**Comment by dokastho** [comment]
thanks for your patience, it should be all set now. It was trying to load a file after hwe when it should have been saving it, then loading
